name: AGMCTM
version: ${project.version}
main: amusingmctm.agmctm.Main
description: This project is My Unko
authors:
  - minnminn119
  - mueru
  - teriyaki
  - Sadaonium
  - Ruin
  - yutanpo
  - yottyan
  - loses
commands:
  agmc:
    description: AGMC Plugin Commands.
    usage: '/agmc [reload]'

permissions:
  agmc.*:
    description: agmc root permission
    children:
      agmc.command: true
  agmc.command:
    description: agmc commands permission
    children:
      agmc.command.reload: true
  agmc.command.reload:
    description: agmc reload command permission
