name: AGMCTM
version: ${project.version}
main: amusingmctm.agmctm.Main
description: This project is My Unko
authors:
  - minnminn119
  - mueru
  - teriyaki
  - Sadaonium
  - Ruin
  - yutanpo
  - yottyan
  - loses
commands:
  AGMCPreload:
    description: Reload the plugin
